name: Traffic Lights Demo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  QT_VERSION: 6.6.2
  OS: linux
  PLATFORM: desktop
  ARCH: gcc_64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      shell: bash
      run: |
        pip install aqtinstall
        python -m aqt install-qt --outputdir ${{github.workspace}}/qt ${{env.OS}} ${{env.PLATFORM}} ${{env.QT_VERSION}} ${{env.ARCH}} -m qtscxml
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=${{github.workspace}}/qt/6.6.2/macos/

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    

